### ISSUE TITLE
epic2

### ISSUE THREAD

**Issue by Finkes** [Finkes/epic-tasks-action#6]
### Linked Issues
- [ ] test ([#1](https://github.com/Finkes/epic-tasks-action/issues/1))
- [x] test ([#2](https://github.com/Finkes/epic-tasks-action/issues/2))
- [ ] ref epic 6 ([#7](https://github.com/Finkes/epic-tasks-action/issues/7))
- [ ] test ref ([#8](https://github.com/Finkes/epic-tasks-action/issues/8))
- [ ] sfsf ([#9](https://github.com/Finkes/epic-tasks-action/issues/9))
- [ ] werwer ([#10](https://github.com/Finkes/epic-tasks-action/issues/10))
- [ ] test ([#11](https://github.com/Finkes/epic-tasks-action/issues/11))
- [x] sdfdaf ([#12](https://github.com/Finkes/epic-tasks-action/issues/12))
### Linked Issues
- [ ] test ([#1](https://github.com/Finkes/epic-tasks-action/issues/1))
- [x] test ([#2](https://github.com/Finkes/epic-tasks-action/issues/2))
- [ ] ref epic 6 ([#7](https://github.com/Finkes/epic-tasks-action/issues/7))
- [ ] test ref ([#8](https://github.com/Finkes/epic-tasks-action/issues/8))
- [ ] sfsf ([#9](https://github.com/Finkes/epic-tasks-action/issues/9))
- [x] werwer ([#10](https://github.com/Finkes/epic-tasks-action/issues/10))
- [ ] test ([#11](https://github.com/Finkes/epic-tasks-action/issues/11))
- [x] sdfdaf ([#12](https://github.com/Finkes/epic-tasks-action/issues/12))

**Comment by Finkes** [comment]
### Linked Issues
- [ ] test ([#1](https://github.com/Finkes/epic-tasks-action/issues/1))
- [x] test ([#2](https://github.com/Finkes/epic-tasks-action/issues/2))
- [ ] ref epic 6 ([#7](https://github.com/Finkes/epic-tasks-action/issues/7))
- [ ] test ref ([#8](https://github.com/Finkes/epic-tasks-action/issues/8))
- [ ] sfsf ([#9](https://github.com/Finkes/epic-tasks-action/issues/9))
- [ ] werwer ([#10](https://github.com/Finkes/epic-tasks-action/issues/10))
- [ ] test ([#11](https://github.com/Finkes/epic-tasks-action/issues/11))
- [x] sdfdaf ([#12](https://github.com/Finkes/epic-tasks-action/issues/12))

**Comment by Finkes** [comment]
test2
